analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.8817204
  brandStrength: 0.5430108
  lightness: 0.8207885
  brandColors:
    - '#BDBCBD'
    - '#151618'
    - '#909A9B'
    - '#4C3926'
    - '#E9F8FC'
  rhythmicContrast: 0.5537634
typography_spectrum: 0.7912403717637062
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0
favicon: null
name: Chef II Hizq
